CREATE TABLE credito (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   credit_code UUID NOT NULL,
   credit_value DECIMAL NOT NULL,
   day_first_instalmente date NOT NULL,
   number_off_instalmente INT NOT NULL,
   status SMALLINT,
   costumer_id BIGINT,
   CONSTRAINT pk_credito PRIMARY KEY (id)
);

ALTER TABLE credito ADD CONSTRAINT uc_credito_credit_code UNIQUE (credit_code);

ALTER TABLE credito ADD CONSTRAINT FK_CREDITO_ON_COSTUMER FOREIGN KEY (costumer_id) REFERENCES customer (id);